const airlineData = [
  {
    id: 1,
    name: "Garuda Indonesia",
    code: "GA",
    baggage: 20,
    cabinBaggage: 7,
    entertainment: "In Flight Entertainment",
    urlImage: "https://example.com/garuda.jpg",
    fileId: "garuda123",
  },
  {
    id: 2,
    name: "Singapore Airlines",
    code: "SQ",
    baggage: 25,
    cabinBaggage: 7,
    entertainment: "KrisWorld Entertainment",
    urlImage: "https://example.com/singapore.jpg",
    fileId: "singapore456"
  },
  {
    id: 3,
    name: "Delta Airlines",
    code: "DL",
    baggage: 23,
    cabinBaggage: 10,
    entertainment: "Delta Studio",
    urlImage: "https://example.com/delta.jpg",
    fileId: "delta789",
  },
  {
    id: 4,
    name: "American Airlines",
    code: "AA",
    baggage: 22,
    cabinBaggage: 8,
    entertainment: "American Airlines Entertainment",
    urlImage: "https://example.com/american.jpg",
    fileId: "american012",
  },
  {
    id: 5,
    name: "United Airlines",
    code: "UA",
    baggage: 24,
    cabinBaggage: 9,
    entertainment: "United Private Screening",
    urlImage: "https://example.com/united.jpg",
    fileId: "united345",
  },
  {
    id: 6,
    name: "British Airways",
    code: "BA",
    baggage: 30,
    cabinBaggage: 7,
    entertainment: "High Life Entertainment",
    urlImage: "https://example.com/british.jpg",
    fileId: "british678",
  },
  {
    id: 7,
    name: "Qatar Airways",
    code: "QR",
    baggage: 30,
    cabinBaggage: 10,
    entertainment: "Oryx One",
    urlImage: "https://example.com/qatar.jpg",
    fileId: "qatar901",
  },
  {
    id: 8,
    name: "Emirates",
    code: "EK",
    baggage: 30,
    cabinBaggage: 7,
    entertainment: "ice Entertainment",
    urlImage: "https://example.com/emirates.jpg",
    fileId: "emirates234",
  },
  {
    id: 9,
    name: "Lufthansa",
    code: "LH",
    baggage: 23,
    cabinBaggage: 8,
    entertainment: "Lufthansa Inflight Entertainment",
    urlImage: "https://example.com/lufthansa.jpg",
    fileId: "lufthansa567",
  },
  {
    id: 10,
    name: "Air France",
    code: "AF",
    baggage: 23,
    cabinBaggage: 10,
    entertainment: "Air France Entertainment",
    urlImage: "https://example.com/airfrance.jpg",
    fileId: "airfrance890",
  },
  {
    id: 11,
    name: "KLM",
    code: "KL",
    baggage: 23,
    cabinBaggage: 10,
    entertainment: "KLM Inflight Entertainment",
    urlImage: "https://example.com/klm.jpg",
    fileId: "klm123",
  },
  {
    id: 12,
    name: "Turkish Airlines",
    code: "TK",
    baggage: 30,
    cabinBaggage: 8,
    entertainment: "Turkish Airlines Entertainment",
    urlImage: "https://example.com/turkish.jpg",
    fileId: "turkish456",
  },
  {
    id: 13,
    name: "JetBlue Airways",
    code: "JB",
    baggage: 23,
    cabinBaggage: 10,
    entertainment: "JetBlue TV",
    urlImage: "https://example.com/jetblue.jpg",
    fileId: "jetblue789",
  },
  {
    id: 14,
    name: "Southwest Airlines",
    code: "WN",
    baggage: 2,
    cabinBaggage: 1,
    entertainment: "In-flight TV",
    urlImage: "https://example.com/southwest.jpg",
    fileId: "southwest012",
  },
  {
    id: 15,
    name: "Alaska Airlines",
    code: "AS",
    baggage: 23,
    cabinBaggage: 10,
    entertainment: "Alaska Beyond Entertainment",
    urlImage: "https://example.com/alaska.jpg",
    fileId: "alaska345",
  },
  {
    id: 16,
    name: "Hawaiian Airlines",
    code: "HA",
    baggage: 50,
    cabinBaggage: 7,
    entertainment: "Hawaiian Airlines Entertainment",
    urlImage: "https://example.com/hawaiian.jpg",
    fileId: "hawaiian678",
  },
  {
    id: 17,
    name: "Alitalia",
    code: "AZ",
    baggage: 23,
    cabinBaggage: 10,
    entertainment: "Alitalia Inflight Entertainment",
    urlImage: "https://example.com/alitalia.jpg",
    fileId: "alitalia901",
  },
  {
    id: 18,
    name: "Austrian Airlines",
    code: "OS",
    baggage: 23,
    cabinBaggage: 10,
    entertainment: "Austrian Inflight Entertainment",
    urlImage: "https://example.com/austrian.jpg",
    fileId: "austrian234",
  },
  {
    id: 19,
    name: "Finnair",
    code: "AY",
    baggage: 23,
    cabinBaggage: 10,
    entertainment: "Finnair Entertainment",
    urlImage: "https://example.com/finnair.jpg",
    fileId: "finnair567",
  },
  {
    id: 20,
    name: "Iberia",
    code: "IB",
    baggage: 23,
    cabinBaggage: 10,
    entertainment: "Iberia Inflight Entertainment",
    urlImage: "https://example.com/iberia.jpg",
    fileId: "iberia890",
  },
  {
    id: 21,
    name: "SAS",
    code: "SK",
    baggage: 23,
    cabinBaggage: 10,
    entertainment: "SAS Inflight Entertainment",
    urlImage: "https://example.com/sas.jpg",
    fileId: "sas123",
  }
]

module.exports = { airlineData }